source:      .
destination: _deploy

collections:
  - sections

colors:
  - name: red
    hex: '#FF263B'
  - name: light-blue
    hex: '#A9F3FB'
  - name: dark-blue
    hex: '#0F2BEA'
  - name: yellow
    hex: '#f8f586'
  - name: purple
    hex: '#6D47D0'
